### ISSUE TITLE
Feature request: add TS types for Modernizr and all its properties

### ISSUE THREAD

**Issue by RubenSibon** [dword-design/nuxt-modernizr#16]
In TypeScript projects the TS compiler will complain about the variable Modernizr not existing on the Window object or globally. It can be solved by adding types manually*, but it would be helpful if this would module provide the types out of the box.

Good to know that community type definitions for Modernizr exist, but do not add them to window (if I am not mistaken): https://www.npmjs.com/package/@types/modernizr

(*) Note: I manually typed the test result for the `<details>` element as follows:

```ts
declare global {
  interface Window {
    Modernizr: {
      details: boolean;
    };
  }
};
```

**Comment by dword-design** [comment]
@RubenSibon Sounds reasonable. Are you up for a PR?

**Comment by RubenSibon** [comment]
@dword-design Ok, I am giving it a shot. No guarantees though.

When including this module locally I noticed that '@dword-design/nuxt-push-plugins' cannot be found as the module [does not seem to exist on npm](https://www.npmjs.com/search?q=%40dword-design%2Fnuxt-push-plugins). To work around that I will directly import the repo.

**Comment by dword-design** [comment]
@RubenSibon Great, looking forward to it!

It does exist, it is just deprecated in favor of `nuxt-push-plugins` without scope. See https://www.npmjs.com/package/@dword-design/nuxt-push-plugins. Deprecated packages can't be found via search.

**Comment by RubenSibon** [comment]
@dword-design, I have been trying to figure out how to provide global types with an npm lib, but no success.

I've tried some of the answers to [this StackOverflow question](https://stackoverflow.com/questions/55659710/how-to-make-an-npm-module-with-globally-accessible-types), but did not manage to get it solved. Maybe you or someone else knows how to?

You can find the branch I was working on here: https://github.com/RubenSibon/nuxt-modernizr/tree/feature/types

**Comment by dword-design** [comment]
@RubenSibon I'm not really into TypeScript yet. I'll probably get into it in the near future, but help from someone who has experience with it would be appreciated.

**Comment by RubenSibon** [comment]
Yeah, based on the StackOverflow answers it seems that it is not a trivial task to add global types. I personally have no experience with creating NPM libraries so anyone who can help with this would be appreciated.

Anyway, for anyone reading this who is using nuxt-modernizr and wants to add the types in their project you can install modernizr and @types/modernizr and add the types like so:

```ts
import Modernizr from 'modernizr'

declare global {
  interface Window {
    Modernizr: typeof Modernizr;
  }
}
```
